// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const EmptyState: typeof import('M:/.systemfile/sync-freedom/extension/src/components/MyTabsPanel').EmptyState
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LockScreen: typeof import('M:/.systemfile/sync-freedom/extension/src/components/LockScreen').LockScreen
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const MyTabsPanel: typeof import('M:/.systemfile/sync-freedom/extension/src/components/MyTabsPanel').MyTabsPanel
  const RemoteTabsPanel: typeof import('M:/.systemfile/sync-freedom/extension/src/components/RemoteTabsPanel').RemoteTabsPanel
  const SettingsPanel: typeof import('M:/.systemfile/sync-freedom/extension/src/components/SettingsPanel').SettingsPanel
  const SetupWizard: typeof import('M:/.systemfile/sync-freedom/extension/src/components/SetupWizard').SetupWizard
  const TabHistoryPanel: typeof import('M:/.systemfile/sync-freedom/extension/src/components/TabHistoryPanel').TabHistoryPanel
  const TabRow: typeof import('M:/.systemfile/sync-freedom/extension/src/components/MyTabsPanel').TabRow
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const debounce: typeof import('M:/.systemfile/sync-freedom/extension/src/utils/debounce').debounce
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getFaviconUrl: typeof import('M:/.systemfile/sync-freedom/extension/src/utils/favicon').getFaviconUrl
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isInternalUrl: typeof import('M:/.systemfile/sync-freedom/extension/src/utils/favicon').isInternalUrl
  const scheduleAlarmDebounce: typeof import('M:/.systemfile/sync-freedom/extension/src/utils/debounce').scheduleAlarmDebounce
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
